<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Module'                        => __DIR__ . '/Module.php',
    'SearchTest\SampleTest'                => __DIR__ . '/tests/Search/SampleTest.php',
    'SearchTest\Framework\TestCase'        => __DIR__ . '/tests/Search/Framework/TestCase.php',
    'ModuleTest'                           => __DIR__ . '/tests/Search/ModuleTest.php',
    'Market\Model\ListingsTable'           => __DIR__ . '/src/Market/Model/ListingsTable.php',
    'Market\Controller\PostController'     => __DIR__ . '/src/Market/Controller/PostController.php',
    'Market\Controller\ViewController'     => __DIR__ . '/src/Market/Controller/ViewController.php',
    'Market\Controller\IndexController'    => __DIR__ . '/src/Market/Controller/IndexController.php',
    'Market\Form\PostFilter'               => __DIR__ . '/src/Market/Form/PostFilter.php',
    'Market\Form\CategoryTrait'            => __DIR__ . '/src/Market/Form/CategoryTrait.php',
    'Market\Form\CaptchaTrait'             => __DIR__ . '/src/Market/Form/CaptchaTrait.php',
    'Market\Form\PostForm'                 => __DIR__ . '/src/Market/Form/PostForm.php',
    'Market\Form\Filter\Float'             => __DIR__ . '/src/Market/Form/Filter/Float.php',
    'Market\Form\ExpireDaysTrait'          => __DIR__ . '/src/Market/Form/ExpireDaysTrait.php',
    'Market\Factory\PostControllerFactory' => __DIR__ . '/src/Market/Factory/PostControllerFactory.php',
    'Market\Factory\PostFormFactory'       => __DIR__ . '/src/Market/Factory/PostFormFactory.php',
    'Market\Factory\PostFilterFactory'     => __DIR__ . '/src/Market/Factory/PostFilterFactory.php',
);
