<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Module'                     => __DIR__ . '/Module.php',
    'SearchTest\SampleTest'             => __DIR__ . '/tests/Search/SampleTest.php',
    'SearchTest\Framework\TestCase'     => __DIR__ . '/tests/Search/Framework/TestCase.php',
    'ModuleTest'                        => __DIR__ . '/tests/Search/ModuleTest.php',
    'Market\Controller\ViewController'  => __DIR__ . '/src/Market/Controller/ViewController.php',
    'Market\Controller\IndexController' => __DIR__ . '/src/Market/Controller/IndexController.php',
);
