<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Search\Module'                        => __DIR__ . '/Module.php',
    'Search\Controller\SearchController'   => __DIR__ . '/src/Search/Controller/SearchController.php',
    'SearchTest\Framework\TestCase'        => __DIR__ . '/tests/Search/Framework/TestCase.php',
    'SearchTest\SampleTest'                => __DIR__ . '/tests/Search/SampleTest.php',
);